import { createHash } from 'node:crypto';
import { createReadStream, existsSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import type { AssetManifest } from './runtime/assets.js';
import { contentType } from './runtime/mime.js';
import { COMPRESSED_ENCODINGS, SIDECAR_EXTENSIONS } from './runtime/negotiate.js';

/** Build-only discovery. Symlinks are excluded so assets cannot escape the output tree. */
export async function createAssetManifest(root: string): Promise<AssetManifest> {
	const manifest: AssetManifest = new Map();
	if (!existsSync(root)) return manifest;
	async function walk(dir: string): Promise<void> {
		const entries = readdirSync(path.join(root, dir), { withFileTypes: true });
		entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
		for (const entry of entries) {
			const relative = dir ? `${dir}/${entry.name}` : entry.name;
			if (entry.isDirectory()) await walk(relative);
			else if (entry.isFile()) {
				const filePath = path.join(root, relative);
				const hash = createHash('sha256');
				let size = 0;
				// Stream one file at a time: even large downloads do not inflate build memory.
				for await (const chunk of createReadStream(filePath)) {
					hash.update(chunk);
					size += chunk.length;
				}
				manifest.set(`/${relative}`, {
					filePath,
					size,
					contentType: contentType(relative),
					etag: `"${hash.digest('base64url')}"`,
					encodings: new Map()
				});
			}
		}
	}
	await walk('');
	for (const [pathname, entry] of manifest) {
		for (const encoding of COMPRESSED_ENCODINGS) {
			const sidecar = manifest.get(pathname + SIDECAR_EXTENSIONS[encoding]);
			if (sidecar) entry.encodings.set(encoding, sidecar);
		}
	}
	return manifest;
}

/** Compact metadata only; pathname occurs once, sidecars share their indexed entry. */
function rows(manifest: AssetManifest) {
	return [...manifest].map(([pathname, entry]) => [
		pathname,
		entry.size,
		entry.contentType,
		entry.etag,
		...(entry.encodings.size ? [[...entry.encodings.keys()]] : [])
	]);
}

/** Emits a relocatable ES module imported directly by handler.js. No runtime discovery. */
export async function writeAssetManifest(out: string): Promise<void> {
	const client = await createAssetManifest(path.join(out, 'client'));
	const prerendered = await createAssetManifest(path.join(out, 'prerendered'));
	writeFileSync(
		path.join(out, 'asset-manifest.js'),
		`// Generated by adapter-hono. Do not edit assets after building.

import { fileURLToPath } from 'node:url';
const extensions = ${JSON.stringify(SIDECAR_EXTENSIONS)};
function assets(root, rows) {
	const manifest = new Map(rows.map(([pathname, size, contentType, etag]) => [pathname, {
		filePath: fileURLToPath(new URL(root + pathname.split('/').map(encodeURIComponent).join('/'), import.meta.url)),
		size, contentType, etag, encodings: new Map()
	}]));
	for (const [pathname, , , , encodings = []] of rows) {
		for (const encoding of encodings) {
			manifest.get(pathname).encodings.set(encoding, manifest.get(pathname + extensions[encoding]));
		}
	}
	return manifest;
}
export const client = assets('./client', ${JSON.stringify(rows(client))});
export const prerendered = assets('./prerendered', ${JSON.stringify(rows(prerendered))});
`
	);
}
